export default {
  never: "أبدا",
  always: "دائما",
  are_you_sure: "هل انت متأكد",
  ok: "موافق",
  cancel: "الغاء",
  creat_group: "انشاء مجموعة",
  create_broadcast: "انشاء برودكاست",
  starred_meassages: "Starred messages",
  archive: "ارشفة",
  settings: "الاعدادات",
  add_contact: "اضافة اتصال",
  camera: "الكميرا",
  photo_video_lib: "مكتبة الصور&الفديوهات",
  document: "المستندات",
  location: "الموقع",
  contcat: "الاتصال",
  mute: "Mute",
  contact_info: "معلوات الاتصال",
  export_chat: "تصدير المحادثات",
  clear_chat: "تنظيف المحادثات",
  delete_chat: "مسح المحادثات",
  report: "تقرير",
  block: "بلوك",
  add_to_group: "اضافة الي المجموعة",
  end_to_end_encrypted: "التشفير التام بين الطرفين",
  calling: "اتصال",
};
