export default {
  account: "الحساب",
  chats: "الشات",
  appereance: "المظهر الخارجي",
  notification: "الاشعارات",
  privacy: "الحماية",
  dataUsage: "استخدام البيانات",
  help: "المساعة",
  inviteFriends: "عوة الاصدقاء",
  security: "الامان",
  twoStepVerification: "التحقق من خططوتين",
  changeNumber: "تغير الرقم",
  changeEmail: "تغير الاميل",
  saveToCameraRoll: "حفظ الي مستندات الكميرا",
  changeWallpaper: "تغير المظهر",
  chatBackup: "حفظ نسخة من المحدثات",
  archiveAllChats: "ارشفة كل المحادثات",
  clearAllChats: "تنظيف المحادثات",
  deleteAllChats: "مسح كل المحادثات",
  chatDesc: "حفظ الصور والفديوهات التي تستلمها الي ذاكرة الموبايل اوتوماتيكي",
  show_notification: "اظهار الاشعارات",
  message_notifiction: "اشعارات الرسائل",
  group_notifiction: "اشعارات المجموعة",
  chat_notifiction: "اشعارات المحادثات",
  sound: "الصوت",
  media_auto_dwonload: "تحميل الوسائط بشكل تلقائي",
  photos: "الصصور",
  audio: "الصوت",
  videos: "الفديو",
  documents: "الملفات",
  rest_download_settings: "الرجوع لاعدادت الافتراضي",
  data_usage_desc: " الرسائل الصوتية تحمل دائما بشكل تلقائي",
  low_data_usage: "استخدام المنخفض للبينات",
  low_data_desc:
    "استخدام اقل بيانات عند المكالمات الفديو او الصوت اثناء استخدام بينات الجوال",
  network_usage: "استخدام النت",
  storage_usage: "استخدام ذاكرة الهاتف",
  save: "حفظ",
  mail: "الاميل",
  connect: "توصيل",
  username: "اسم المستخدم",
  phone: "الهاتف",
  website: "موقع الانترنت",
  pay: "الدفع",
  description: "الوصف",
};
