export default {
  home: "Home",
  call: "Call",
  chat: "Chat",
  settings: "Settings",

  more: "More",
  wifi_and_cellular: "wi-fi and cellular",
  wifi: "wi-fi",
  cellular: "cellular",
  create_new_account: "Create New Account",
  login_title: "Login",
  signup_goolge: "Signup with Google",
  signup_facebook: "Signup with Facebook",
  signup_email: "Signup with Email",
  login_goolge: "Login with Google",
  login_facebook: "Login with Facebook",
  login_email: "Login with Email",
  already_have_account: "You already have an account",
  dont_have_account: "create new account",
};
