export default {
  never: "Never",
  always: "Always",
  are_you_sure: "Are you sure",
  ok: "Ok",
  cancel: "Cancel",
  creat_group: "Create group",
  create_broadcast: "Create broadcast",
  starred_meassages: "Starred messages",
  archive: "Archive",
  settings: "Settings",
  add_contact: "Add Contact",
  camera: "Camera",
  photo_video_lib: "Photo&Video Library",
  document: "Document",
  location: "Location",
  contcat: "Contact",
  mute: "Mute",
  contact_info: "Contact Info",
  export_chat: "Export Chat",
  clear_chat: "Clear Chat",
  delete_chat: "Delete Chat",
  report: "Report",
  block: "Block",
  add_to_group: "Add to group",
  end_to_end_encrypted: "End-to-end encrypted",
  calling: "Calling",
};
