export default {
  account: "Account",
  chats: "Chats",
  appereance: "Appereance",
  notification: "Notification",
  privacy: "Privacy",
  dataUsage: "Data Usage",
  help: "Help",
  inviteFriends: "Invite Your Friends",
  security: "Security",
  twoStepVerification: "two-Step-verification",
  changeNumber: "Change Number",
  changeEmail: "Change Email",
  saveToCameraRoll: "Save to Camera Roll",
  changeWallpaper: "Change Wallpaper",
  chatBackup: "Chat Backup",
  archiveAllChats: "Archive All Chats",
  clearAllChats: "Clear All Chats",
  deleteAllChats: "Delete All Chats",
  chatDesc:
    "Automatically save photos and videos you receive to your iPhone's Camera Roll.",
  show_notification: "Show Notifications",
  message_notifiction: "Message notifications",
  group_notifiction: "Group notifications",
  chat_notifiction: "Chat notifications",
  sound: "Sound",
  media_auto_dwonload: "Media auto-download",
  photos: "Photos",
  audio: "Audio",
  videos: "Videos",
  documents: "Documents",
  rest_download_settings: "Reset Auto-Download Settings",
  data_usage_desc:
    "Voice Messages are always automatically downloaded for the best communication experience.",
  low_data_usage: "Low Data Usage",
  low_data_desc:
    "Lower the amount of data used during a Void call on cellular.",
  network_usage: "Network Usage",
  storage_usage: "Storage Usage",
  save: "Save",
  mail: "Mail",
  connect: "Connect",
  username: "username",
  phone: "Phone",
  website: "Website",
  pay: "Pay",
  description: "description",
};
