export const convrsations = [
  {
    id: 1,
    name: "user1",
    message: "Sed ligula erat, dignissim sit at amet dictum id, iaculis",
    createAt: "1hour",
    numofMessages: 3,
  },
  {
    id: 2,
    name: "user2",
    message: "Sed ligula erat, dignissim sit at amet dictum id, iaculis",
    createAt: "16 min",
    numofMessages: 0,
  },
  {
    id: 3,
    name: "user3",
    message: "Sed ligula erat, dignissim sit at amet dictum id, iaculis",
    createAt: "32 min",
    numofMessages: 2,
  },
  {
    id: 4,
    name: "user3",
    message: "Sed ligula erat, dignissim sit at amet dictum id, iaculis",
    createAt: "32 min",
    numofMessages: 2,
  },
  {
    id: 5,
    name: "user3",
    message: "Sed ligula erat, dignissim sit at amet dictum id, iaculis",
    createAt: "32 min",
    numofMessages: 2,
  },
  {
    id: 6,
    name: "user3",
    message: "Sed ligula erat, dignissim sit at amet dictum id, iaculis",
    createAt: "32 min",
    numofMessages: 2,
  },
];
export const notification = [
  {
    id: 1,
    name: "user1",
    message: "Sed ligula erat, dignissim sit at amet dictum id, iaculis",
    createAt: "1hour",
    action: "add",
    goupName: "group1",
    groupMembers: 10,
    notificationType: "group",
  },
  {
    id: 2,
    name: "user2",
    message: "Sed ligula erat, dignissim sit at amet dictum id, iaculis",
    createAt: "16 min",
    action: "remove",
    actionType: "video",
    notificationType: "call",
  },
  {
    id: 3,
    name: "user3",
    message: "Sed ligula erat, dignissim sit at amet dictum id, iaculis",
    createAt: "16 min",
    action: "call",
    actionType: "calling",
    notificationType: "call",
  },
  {
    id: 4,
    name: "user3",
    message: "Sed ligula erat, dignissim sit at amet dictum id, iaculis",
    createAt: "32 min",
    action: "call",
    goupName: "group9",
    groupMembers: 10,
    notificationType: "group",
  },
];
export const calls = [
  {
    id: 1,
    name: "user1",
    createdAt: "1hour",
    actionType: "calling",
    calling: true,
  },
  {
    id: 2,
    name: "user2",
    createdAt: "10min",
    actionType: "video",
    calling: false,
  },
  {
    id: 3,
    name: "user3",
    createdAt: "15min",
    actionType: "calling",
    calling: false,
  },
  {
    id: 4,
    name: "user4",
    createdAt: "10hour",
    actionType: "video",
    calling: true,
  },
];

export const messages = [
  {
    id: 1,
    userId: 2,
    message: "Import the new use Redux Dispatch and use ",
    createdAt: "2 min",
    messageType: "text",
  },
  {
    id: 2,
    userId: 1,
    message:
      "Import the new useReduxDispatch and useReduxSelector and use them to dispatch actions on button click and link the counter with the current",
    createdAt: "2 min",
    messageType: "text",
  },
  {
    id: 3,
    userId: 2,
    message: "Import the new use Redux Dispatch and use ",
    createdAt: "2 min",
    messageType: "text",
  },
  {
    id: 4,
    userId: 1,
    message: "مرحبا اخي العزيز ",
    createdAt: "2 min",
    messageType: "text",
  },
  {
    id: 5,
    userId: 1,
    createdAt: "2 min",
    messageType: "sound",
    url: "http://codeskulptor-demos.commondatastorage.googleapis.com/pang/paza-moduless.mp3",
  },
  {
    id: 6,
    userId: 2,
    createdAt: "2 min",
    messageType: "sound",
    uri: "http://codeskulptor-demos.commondatastorage.googleapis.com/pang/paza-moduless.mp3",
  },
  {
    id: 7,
    userId: 2,
    createdAt: "2 min",
    messageType: "image",
    images: [
      "https://thumbs.dreamstime.com/z/beautiful-rain-forest-ang-ka-nature-trail-doi-inthanon-national-park-thailand-36703721.jpg",
      "https://thumbs.dreamstime.com/z/rain-forest-walk-way-ang-ka-nature-trail-located-doi-inthanon-national-park-highest-peak-thailand-79248764.jpg",
      "https://thumbs.dreamstime.com/z/rain-forest-25076143.jpg",
    ],
  },
  {
    id: 8,
    userId: 3,
    createdAt: "2 min",
    messageType: "video",
    uri: "https://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4",
  },
];
